version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run: echo Hello PR!
      - run: echo Hello PR!
      - run: echo Hello PR!
      - run: echo Hello PR!
      - run: exit
